url: https://ajkl.github.io
baseurl: /wedding-invite/

# Site settings
title: Payal&nbsp;&nbsp;&#9829;&nbsp;&nbsp;Ajinkya
email: kaleajinkya@gmail.com
description: "Git pages hosted Wedding Invitation"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Vijaya Kale
  pic: 1
  position: Var Mai

- name: Gorakhnath Kale
  pic: 2
  position: Var Pita

- name: Diana Somne
  pic: 3
  position: Vadhu Mata

- name: Prakash Somne
  pic: 2
  position: Vadhu Pita
  
- name: Raviraj Kale
  pic: 1
  position: Var Bhau

- name: Snehal Kale
  pic: 2
  position: Var Vahini

- name: Parag Somne
  pic: 3
  position: Vadhu Bhau

- name: Shalaka Somne
  pic: 1
  position: Vadhu Vahini

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/ajinkyakale
  - title: github
    url: http://github.com/ajkl

# Build settings
markdown: kramdown
permalink: pretty
